# Generated by Django 5.1.15 on 2026-09-13 22:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('diretor', 'Diretor'), ('vice_diretor', 'Vice-diretor'), ('secretaria', 'Secretaria'), ('professor', 'Professor'), ('responsavel', 'Responsável'), ('aluno', 'Aluno')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gestor', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('departamento', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='responsavel', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('cpf', models.CharField(blank=True, max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='professor', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('materia', models.CharField(blank=True, choices=[('lingua_portuguesa', 'Língua Portuguesa'), ('matematica', 'Matemática'), ('historia', 'História'), ('geografia', 'Geografia'), ('ciencias', 'Ciências'), ('lingua_inglesa', 'Língua Inglesa'), ('arte', 'Arte'), ('educacao_fisica', 'Educação Física')], help_text='Disciplina principal lecionada', max_length=30)),
                ('formacao', models.CharField(blank=True, max_length=200)),
                ('turmas', models.ManyToManyField(blank=True, related_name='professores', to='turmas.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='aluno', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ra', models.CharField(max_length=30, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='turmas.turma')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='accounts.responsavel')),
            ],
        ),
    ]
