# Generated by Django 5.1.15 on 2026-09-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(choices=[('lingua_portuguesa', 'Língua Portuguesa'), ('matematica', 'Matemática'), ('historia', 'História'), ('geografia', 'Geografia'), ('ciencias', 'Ciências'), ('lingua_inglesa', 'Língua Inglesa'), ('arte', 'Arte'), ('educacao_fisica', 'Educação Física')], max_length=30)),
                ('b1', models.PositiveSmallIntegerField(default=0)),
                ('b2', models.PositiveSmallIntegerField(default=0)),
                ('b3', models.PositiveSmallIntegerField(default=0)),
                ('b4', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ano_letivo'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(choices=[('lingua_portuguesa', 'Língua Portuguesa'), ('matematica', 'Matemática'), ('historia', 'História'), ('geografia', 'Geografia'), ('ciencias', 'Ciências'), ('lingua_inglesa', 'Língua Inglesa'), ('arte', 'Arte'), ('educacao_fisica', 'Educação Física')], max_length=30)),
                ('b1', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('b2', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('b3', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('b4', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
