# Generated by Django 5.1.15 on 2026-09-13 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('accounts', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='accounts.aluno'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='turmas.turma'),
        ),
        migrations.AddField(
            model_name='falta',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='academico.matricula'),
        ),
        migrations.AddField(
            model_name='nota',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academico.matricula'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('aluno', 'ano_letivo')},
        ),
        migrations.AlterUniqueTogether(
            name='falta',
            unique_together={('matricula', 'materia')},
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('matricula', 'materia')},
        ),
    ]
