# Generated by Django 5.1.15 on 2026-09-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: "5-A", "9-D"', max_length=10)),
                ('ano_letivo', models.PositiveSmallIntegerField()),
                ('turno', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ano_letivo', 'nome'],
                'unique_together': {('nome', 'ano_letivo')},
            },
        ),
    ]
